<?php
$products=array();
$temp1= array();
$temp1['Version'] = '1.1'; 
$temp2=array();
$temp2['Version'] = '1.1';
array_push($products, $temp1);
array_push($products, $temp2);
$temp = array();
 $temp['Version'] = '1.1'; 
 $temp['TranDtls']['TaxSch'] = 'tax'; 
 $temp['TranDtls']['SupTyp'] = 'tax'; 
 $temp['TranDtls']['IgstOnIntra'] = 'tax'; 
 $temp['TranDtls']['RegRev'] = 'tax'; 
 $temp['TranDtls']['EcmGstin'] = 'tax'; 
 $temp['DocDtls']['Typ'] = 'INV';
 $temp['DocDtls']['No'] = 'tax';
 $temp['DocDtls']['Dt'] = 'tax';
  $temp['SellerDtls']['Gstin'] = 'tax';
  $temp['SellerDtls']['LglNm'] = 'tax';
  $temp['SellerDtls']['Addr1'] = 'tax';
  $temp['SellerDtls']['Addr2'] = 'tax';
  $temp['SellerDtls']['Loc'] = 'tax';
  $temp['SellerDtls']['Pin'] = 'tax';
    $temp['SellerDtls']['Stcd'] = 'tax';
    $temp['SellerDtls']['Ph'] = 'tax';
  $temp['SellerDtls']['Em'] = 'tax';
   $temp['BuyerDtls']['Gstin'] = 'tax';
    $temp['BuyerDtls']['LglNm'] = 'tax';
     $temp['BuyerDtls']['Addr1'] = 'tax';
      $temp['BuyerDtls']['Addr2'] = 'tax';
       $temp['BuyerDtls']['Loc'] = 'tax';
        $temp['BuyerDtls']['Pin'] = 'tax';
         $temp['BuyerDtls']['Pos'] = 'tax';
          $temp['BuyerDtls']['Stcd'] = 'tax';
           $temp['BuyerDtls']['Ph'] = 'tax';
             $temp['BuyerDtls']['Em'] = 'tax';
    $temp['ValDtls']['AssVal'] = 'tax';
    $temp['ValDtls']['IgstVal'] = 'tax';
    $temp['ValDtls']['CgstVal'] = 'tax';
    $temp['ValDtls']['SgstVal'] = 'tax';
    $temp['ValDtls']['CesVal'] = 'tax';
    $temp['ValDtls']['StCesVal'] = 'tax';
    $temp['ValDtls']['Discount'] = 'tax';
    $temp['ValDtls']['OthChrg'] = 'tax';
    $temp['ValDtls']['RndOffAmt'] = 'tax';
    $temp['ValDtls']['TotInvVal'] = 'tax';
    
     $temp['RefDtls']['InvRm'] = 'tax';
      $temp['ItemList'] = $products;
 echo json_encode($temp);
 ?>